### ISSUE TITLE
Requirements file please

### ISSUE THREAD

**Issue by andreaschandra** [ardianumam/Tensorflow-TensorRT#1]
Dear our famous and glorious author,

I am glad there is someone using TensorRT. But could you please add requirements.txt, so that I would not be facing error like "no module named <lib>" while I was running the notebooks

Thanks

**Comment by ardianumam** [comment]
Dear our awesome Warung Pintar machine learner,

I should set this repo private first until I finish all the things including video editing for the video series. lol.  
Btw, thanks for pointing that out. Yes, I will add it soon once all the things are ready.

Thanks.

**Comment by ardianumam** [comment]
Hi @andreaschandra . I've added the requirements in the readme file. I'll close this issue then. Thanks for reporting.
