### ISSUE TITLE
Instaling Tensorflow 1.11 Jetson TX2

### ISSUE THREAD

**Issue by RogerAylagas** [ardianumam/Tensorflow-TensorRT#11]
Hi I just wantted to ask how did you install the Tensorflow 1.11 in the Jetson TX2

**Comment by ardianumam** [comment]
Hi, I already provided the tutorial link in the readme file on this repo. Pls read it. It's linked to my medium post (or you can access [here](https://medium.com/@ardianumam/installing-tensorrt-in-jetson-tx2-8d130c4438f5)).
