### ISSUE TITLE
Changing number of classes of YOLOv3

### ISSUE THREAD

**Issue by RogerAylagas** [ardianumam/Tensorflow-TensorRT#12]
Hi,
I wanna know how would the line `your_outputs = ["Placeholder:0", "concat_9:0", "mul_9:0"]` if instead of having 10 classes as output we only have 4 classes
An error is appearing when I convert my graph to the trt graph

> Cannot assign a device for operation 'unstack_9': Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
> Registered kernels:
>   device='CPU'; T in [DT_VARIANT]
>   device='CPU'; T in [DT_RESOURCE]
>   device='CPU'; T in [DT_STRING]
>   device='CPU'; T in [DT_BOOL]
>   device='CPU'; T in [DT_COMPLEX128]
>   device='CPU'; T in [DT_COMPLEX64]
>   device='CPU'; T in [DT_DOUBLE]
>   device='CPU'; T in [DT_FLOAT]
>   device='CPU'; T in [DT_BFLOAT16]
>   device='CPU'; T in [DT_HALF]
>   device='CPU'; T in [DT_INT8]
>   device='CPU'; T in [DT_UINT8]
>   device='CPU'; T in [DT_INT16]
>   device='CPU'; T in [DT_UINT16]
>   device='CPU'; T in [DT_INT32]
>   device='CPU'; T in [DT_INT64]
>   device='GPU'; T in [DT_INT64]
>   device='GPU'; T in [DT_INT32]
>   device='GPU'; T in [DT_BFLOAT16]
>   device='GPU'; T in [DT_DOUBLE]
>   device='GPU'; T in [DT_FLOAT]
>   device='GPU'; T in [DT_HALF]
> 
> 	[[{{node unstack_9}} = Unpack[T=DT_STRING, axis=0, num=24, _device="/device:GPU:0"](prefetch_queue_Dequeue:9)]]

Thank you

**Comment by ardianumam** [comment]
Hi, Are you familiar with Tensorflow (TF)? It's exactly same with frozen model in tensorflow. When you are going to do inference, you need to specify which tensors are the input and outputs, so ```["Placeholder:0", "concat_9:0", "mul_9:0"]``` are the in-out tensor used in this repo. You can specify the tensor names with yours.
