### ISSUE TITLE
trt_engine_nodes in TensorRT graph: 0

### ISSUE THREAD

**Issue by ruyijidan** [ardianumam/Tensorflow-TensorRT#18]
TensorRT model is successfully stored!
numb. of all_nodes in frozen graph: 8016
numb. of trt_engine_nodes in TensorRT graph: 0
numb. of all_nodes in TensorRT graph: 882

I don’t know why the model have no TensorRT graph and the trt model FPS is the same as original‘s.
at UBUNTU1804  1080TI tensorRT=5.1.5.0 tensorflow==1.14.0

**Comment by float123** [comment]
I also encountered the same problem
I was thinking that maybe tenflow did not successfully use tensorrt
![image](https://user-images.githubusercontent.com/39334643/60953508-dbec5600-a32f-11e9-9a7c-f07c922ff613.png)
![image](https://user-images.githubusercontent.com/39334643/60953521-e3136400-a32f-11e9-96ec-737f7782bd2f.png)
Environment :
ubuntu1604; 2080ti; TensorRT=5.1.5.0; tensorflow==1.14

**Comment by ruyijidan** [comment]
@float123 
Environment :ubuntu1804 python3.5.6  cuda10.0 cudnn7.5.1.10 Tensorflow1.13,.1 TensorRT5.1.5.0 

WARNING:tensorflow:TensorRT mismatch. Compiled against version 5.0.2, but loaded 5.1.5. Things may not work

TensorRT model is successfully stored!
numb. of all_nodes in frozen graph: 8016
numb. of trt_engine_nodes in TensorRT graph: 18
numb. of all_nodes in TensorRT graph: 73

FYI

**Comment by float123** [comment]
> @float123
> Environment :ubuntu1804 python3.5.6 cuda10.0 cudnn7.5.1.10 Tensorflow1.13,.1 TensorRT5.1.5.0
> 
> WARNING:tensorflow:TensorRT mismatch. Compiled against version 5.0.2, but loaded 5.1.5. Things may not work
> 
> TensorRT model is successfully stored!
> numb. of all_nodes in frozen graph: 8016
> numb. of trt_engine_nodes in TensorRT graph: 18
> numb. of all_nodes in TensorRT graph: 73
> 
> FYI

thank you，I use tensorflow1.13.1 and tensorrt5.0.2.6, but fps also not improve significantly.
![image](https://user-images.githubusercontent.com/39334643/61036472-c2184500-a3fb-11e9-85fc-c82b04577cde.png)

**Comment by ruyijidan** [comment]
The samne as you,But I use my laptop,fps from 10 upto 18~19(GPU 970M),

**Comment by ruyijidan** [comment]
> > @float123
> > Environment :ubuntu1804 python3.5.6 cuda10.0 cudnn7.5.1.10 Tensorflow1.13,.1 TensorRT5.1.5.0
> > WARNING:tensorflow:TensorRT mismatch. Compiled against version 5.0.2, but loaded 5.1.5. Things may not work
> > TensorRT model is successfully stored!
> > numb. of all_nodes in frozen graph: 8016
> > numb. of trt_engine_nodes in TensorRT graph: 18
> > numb. of all_nodes in TensorRT graph: 73
> > FYI
> 
> thank you，I use tensorflow1.13.1 and tensorrt5.0.2.6, but fps also not improve significantly.
> ![image](https://user-images.githubusercontent.com/39334643/61036472-c2184500-a3fb-11e9-85fc-c82b04577cde.png)

The samne as you,But I use my laptop,fps from 10 upto 18~19(GPU 970M),

**Comment by ruyijidan** [comment]
> > @float123
> > Environment :ubuntu1804 python3.5.6 cuda10.0 cudnn7.5.1.10 Tensorflow1.13,.1 TensorRT5.1.5.0
> > WARNING:tensorflow:TensorRT mismatch. Compiled against version 5.0.2, but loaded 5.1.5. Things may not work
> > TensorRT model is successfully stored!
> > numb. of all_nodes in frozen graph: 8016
> > numb. of trt_engine_nodes in TensorRT graph: 18
> > numb. of all_nodes in TensorRT graph: 73
> > FYI
> 
> thank you，I use tensorflow1.13.1 and tensorrt5.0.2.6, but fps also not improve significantly.
> ![image](https://user-images.githubusercontent.com/39334643/61036472-c2184500-a3fb-11e9-85fc-c82b04577cde.png)

The same as you,But I use my laptop,fps from 10 upto 18~19(GPU 970M),
