### ISSUE TITLE
how to get tf format for custom yolo weights

### ISSUE THREAD

**Issue by LukeAI** [ardianumam/Tensorflow-TensorRT#3]
Thanks a lot for this highly educational repo!

I would like to train my own Yolov3 model and try implementing as a TRT engine in the way that you have. How would you recommend doing so? Did you use a TF implementation of Yolov3 to generate your weights or did you convert from the darknet .weights / .cfg ? Whichever approach, I'd be interested to know which specific repos / tools you used to do it?

**Comment by ardianumam** [comment]
It's generated using [this repo](https://github.com/ardianumam/tensorflow-yolov3), which is forked from someone repo mentioned there in the readme file. It converts original darknet weights (as described in the repo). If you wanna train your own YOLOv3 and wanna optimize it using TensorRT, you can just store your YOLOv3 model in frozen model, then optimize that frozen model to TensorRT. Please see the video series for the detail. I already show and explain the detail there :)

**Comment by LukeAI** [comment]
I'm closing this issue, but this is a question I can imagine others asking so could also be useful info for the Readme? :)
