### ISSUE TITLE
Baseline configuration

### ISSUE THREAD

**Issue by filipski** [ardianumam/Tensorflow-TensorRT#4]
Hi,

Please update the README.md with the description of your environment. I know from your last video that you're running probably on desktop with GTX 1060, but which versions of NVIDIA drivers, CUDA , cuDNN and TensorRT?
Similarly, provide you setup for Jetson, please.

**Comment by ardianumam** [comment]
Hi,

Thanks for pointing it out. Now, it's added.

**Comment by filipski** [comment]
Thanks! Closing this one then.
