### ISSUE TITLE
using other models from TensorFlow object detection zoo.

### ISSUE THREAD

**Issue by isra60** [ardianumam/Tensorflow-TensorRT#8]
Hi I'm trying to use other models from 

https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md

But I don't know if the jupyter code is compatible with this?? For example with ssd_mobilenet 2.
The tar.gz that you download has other files apart from interference_graph.pb like meta files and checkpoint.

**Comment by ardianumam** [comment]
TensorRT pb model is exactly same with standard tensorflow (TF) pb model (in term of how we use it for inference). If you can use TF zoo pb model for inference, then, yes, you can optimize to TensorRT pb model and use it for inference with possibly higher FPS.
